import { getSupabaseClient } from '../supabaseClient';
import { ticketRepository } from './ticketRepository';
import { isInvalidUuidError } from './pgErrors';
import type { Attachment, Role } from '../../models/types';

export interface CreateAttachmentInput {
  id: string;
  fileName: string;
  storagePath: string;
  mimeType: string;
  size: number;
  topic: string;
  ticketId: string | null;
  messageId: string | null;
  uploadedBy: string;
  uploadedByName: string;
  uploadedByRole: Role;
}

interface AttachmentRow {
  id: string;
  file_name: string;
  storage_path: string;
  mime_type: string;
  size: number;
  topic: string;
  ticket_id: string | null;
  message_id: string | null;
  uploaded_by: string;
  uploaded_by_name: string;
  uploaded_by_role: Role;
  created_at: string;
}

function fromRow(row: AttachmentRow): Attachment {
  return {
    id: row.id,
    fileName: row.file_name,
    storagePath: row.storage_path,
    mimeType: row.mime_type,
    size: row.size,
    topic: row.topic,
    ticketId: row.ticket_id,
    messageId: row.message_id,
    uploadedBy: row.uploaded_by,
    uploadedByName: row.uploaded_by_name,
    uploadedByRole: row.uploaded_by_role,
    createdAt: row.created_at,
  };
}

export const attachmentRepository = {
  async listAll(): Promise<Attachment[]> {
    const { data, error } = await getSupabaseClient()
      .from('attachments')
      .select('*')
      .order('created_at', { ascending: false });
    if (error) throw error;
    return (data as AttachmentRow[]).map(fromRow);
  },

  async listForTicket(ticketId: string): Promise<Attachment[]> {
    const { data, error } = await getSupabaseClient()
      .from('attachments')
      .select('*')
      .eq('ticket_id', ticketId)
      .order('created_at', { ascending: false });
    if (error) throw error;
    return (data as AttachmentRow[]).map(fromRow);
  },

  // Everything a normal user is allowed to see in the File Repository: any
  // file they personally uploaded (even one not tied to a ticket), plus any
  // file — theirs or the admin's — attached to a ticket they submitted.
  // Admin visibility is just listAll(); callers pick based on role.
  async listVisibleToUser(userId: string): Promise<Attachment[]> {
    const ownTickets = await ticketRepository.listByUser(userId);
    const ownTicketIds = ownTickets.map((t) => t.id);

    // PostgREST .or() needs both branches in one filter string; an empty
    // ticket_id.in.() would be invalid syntax, so build the ticket-id
    // branch only when the user actually has tickets.
    const filters = [`uploaded_by.eq.${userId}`];
    if (ownTicketIds.length > 0) {
      filters.push(`ticket_id.in.(${ownTicketIds.join(',')})`);
    }

    const { data, error } = await getSupabaseClient()
      .from('attachments')
      .select('*')
      .or(filters.join(','))
      .order('created_at', { ascending: false });
    if (error) throw error;
    return (data as AttachmentRow[]).map(fromRow);
  },

  async findById(id: string): Promise<Attachment | undefined> {
    const { data, error } = await getSupabaseClient().from('attachments').select('*').eq('id', id).maybeSingle();
    if (error) {
      if (isInvalidUuidError(error)) return undefined;
      throw error;
    }
    return data ? fromRow(data as AttachmentRow) : undefined;
  },

  async create(input: CreateAttachmentInput): Promise<Attachment> {
    // id is generated by the caller (see server/src/utils/id.ts) and
    // passed in explicitly, BEFORE the file is uploaded to Supabase
    // Storage — see server/src/middleware/upload.ts — so a storage upload
    // failure never leaves an orphan metadata row with no file behind it
    // (nothing is inserted here until the upload already succeeded).
    const { data, error } = await getSupabaseClient()
      .from('attachments')
      .insert({
        id: input.id,
        file_name: input.fileName,
        storage_path: input.storagePath,
        mime_type: input.mimeType,
        size: input.size,
        topic: input.topic,
        ticket_id: input.ticketId,
        message_id: input.messageId,
        uploaded_by: input.uploadedBy,
        uploaded_by_name: input.uploadedByName,
        uploaded_by_role: input.uploadedByRole,
      })
      .select('*')
      .single();
    if (error) throw error;
    return fromRow(data as AttachmentRow);
  },

  async deleteByUploader(userId: string): Promise<void> {
    const { error } = await getSupabaseClient().from('attachments').delete().eq('uploaded_by', userId);
    if (error) throw error;
  },

  async delete(id: string): Promise<Attachment | undefined> {
    const { data, error } = await getSupabaseClient().from('attachments').delete().eq('id', id).select('*').maybeSingle();
    if (error) {
      if (isInvalidUuidError(error)) return undefined;
      throw error;
    }
    return data ? fromRow(data as AttachmentRow) : undefined;
  },
};
